// Purpose: Pure game state transitions plus the local host/player HTTP transport.
import{randomInt}from'node:crypto';import{readFile,writeFile}from'node:fs/promises';import{createServer}from'node:http';import{estimateCostUsd}from'./jev-client.mjs';export{createFakeProvider,createJevClient}from'./jev-client.mjs';
export function createGame({rounds=5,timerSeconds=60,code='000000'}={}){if(!Number.isInteger(rounds)||rounds<1)throw new TypeError('rounds must be positive');return{code,phase:'lobby',round:0,rounds,timerSeconds,players:{},submissions:{},judgments:{},scoreboard:{jev:0,players:{}}}}
export function join(game,name){if(game.phase!=='lobby')throw new Error('game already started');const clean=String(name).trim();if(!clean||Object.values(game.players).includes(clean))throw new Error('name must be non-empty and unique');const id=`p${Object.keys(game.players).length+1}`;game.players[id]=clean;game.scoreboard.players[id]=0;return id}
export function transition(game,event){if(event==='start'&&game.phase==='lobby'){if(!Object.keys(game.players).length)throw new Error('at least one player required');game.phase='collect';game.round=1;return game}if(event==='judge'&&game.phase==='collect'){game.phase='judge';return game}if(event==='reveal'&&game.phase==='judge'){game.phase='reveal';for(const[id,s]of Object.entries(game.submissions)){const guessed=game.judgments[id]?.choice,correct=guessed===String(s.lie);if(correct)game.scoreboard.jev++;else game.scoreboard.players[id]++}return game}if(event==='next'&&game.phase==='reveal'){if(game.round>=game.rounds){game.phase='finished'}else{game.round++;game.phase='collect';game.submissions={};game.judgments={}}return game}throw new Error(`invalid transition ${game.phase} -> ${event}`)}
export function submit(game,playerId,statements,lie){if(game.phase!=='collect'||!game.players[playerId])throw new Error('submission is not open');if(!Array.isArray(statements)||statements.length!==3||statements.some(x=>!String(x).trim())||![0,1,2].includes(lie))throw new Error('submit exactly three statements and one lie index');if(game.submissions[playerId])throw new Error('player already submitted');game.submissions[playerId]={statements:[...statements],lie};return Object.keys(game.submissions).length===Object.keys(game.players).length}
export async function judge(game,provider){if(game.phase!=='judge')throw new Error('game is not in judge phase');const entries=Object.entries(game.submissions);await Promise.all(entries.map(async([id,s])=>{const criteria=Object.fromEntries(s.statements.map((_,i)=>[String(i),null]));const r=await provider({state:{statements:s.statements},questions:{lie:{type:'choice',instructions:'Which of these three statements is most likely false?',criteria}}});game.judgments[id]=r.answers.lie;game.judgments[id].usage=r.usage}));return entries.length}
export function generateJoinCode(existing=new Set(),random=()=>randomInt(0,1_000_000)){for(let i=0;i<100;i++){const c=String(random()).padStart(6,'0');if(!existing.has(c))return c}throw new Error('could not allocate a unique join code')}
export async function saveGame(game,path){await writeFile(path,`${JSON.stringify(game,null,2)}\n`,{mode:0o600});return path}export async function loadGame(path){return JSON.parse(await readFile(path,'utf8'))}
function publicState(g){return{code:g.code,phase:g.phase,round:g.round,rounds:g.rounds,players:g.players,scoreboard:g.scoreboard,...(g.phase==='reveal'||g.phase==='finished'?{submissions:g.submissions,judgments:g.judgments}:{})}}async function body(req){const c=[];for await(const x of req)c.push(x);return JSON.parse(Buffer.concat(c))}function send(res,s,t,x){res.writeHead(s,{'content-type':`${t}; charset=utf-8`});res.end(x)}
export function createGameServer({game,provider}={}){let lock=Promise.resolve();const mutate=fn=>lock=lock.then(fn,fn);return createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/')return send(res,200,'text/html',hostHtml);if(req.method==='GET'&&u.pathname==='/play')return send(res,200,'text/html',playHtml);if(req.method==='GET'&&u.pathname==='/state')return send(res,200,'application/json',JSON.stringify(publicState(game)));if(req.method==='POST'&&u.pathname==='/join'){const x=await body(req),id=await mutate(()=>join(game,x.name));return send(res,200,'application/json',JSON.stringify({id,code:game.code}))}if(req.method==='POST'&&u.pathname==='/submit'){const x=await body(req);await mutate(()=>submit(game,x.playerId,x.statements,x.lie));return send(res,200,'application/json','{"ok":true}')}if(req.method==='POST'&&u.pathname==='/action'){const x=await body(req);await mutate(async()=>{transition(game,x.action);if(x.action==='judge')await judge(game,provider)});return send(res,200,'application/json',JSON.stringify(publicState(game)))}send(res,404,'application/json','{"error":"not_found"}')}catch(e){send(res,400,'application/json',JSON.stringify({error:e.message}))}})}
const hostHtml='<!doctype html><title>Jev Bluff Call</title><style>body{font:22px system-ui;max-width:800px;margin:50px auto;background:#16121f;color:#fff}button{font:inherit;padding:10px;margin:5px;background:#ffca4b;border:0}</style><h1>Bluff Call</h1><p>Players join at <b>/play</b></p><div id=o></div><button onclick="act(`start`)">Start</button><button onclick="act(`judge`)">Judge</button><button onclick="act(`reveal`)">Reveal</button><button onclick="act(`next`)">Next</button><script>async function draw(){o.textContent=JSON.stringify(await(await fetch(`/state`)).json(),null,2)}async function act(action){await fetch(`/action`,{method:`POST`,headers:{`content-type`:`application/json`},body:JSON.stringify({action})});draw()}setInterval(draw,1000);draw()</script>';
const playHtml='<!doctype html><title>Play Bluff Call</title><style>body{font:20px system-ui;max-width:600px;margin:40px auto}input,button{font:inherit;padding:9px;margin:4px;width:90%}</style><h1>Two truths. One lie.</h1><input id=n placeholder="Name"><button onclick="j()">Join</button><input class=s placeholder="Statement 1"><input class=s placeholder="Statement 2"><input class=s placeholder="Statement 3"><input id=l type=number min=1 max=3 value=3><button onclick="send()">Submit privately</button><p id=o></p><script>let id;async function j(){let r=await fetch(`/join`,{method:`POST`,headers:{`content-type`:`application/json`},body:JSON.stringify({name:n.value})});let x=await r.json();id=x.id;o.textContent=`Joined game ${x.code}`}async function send(){let statements=[...document.querySelectorAll(`.s`)].map(x=>x.value);let r=await fetch(`/submit`,{method:`POST`,headers:{`content-type`:`application/json`},body:JSON.stringify({playerId:id,statements,lie:+l.value-1})});o.textContent=r.ok?`Submitted privately`:`Could not submit`}</script>';
export function estimatedGameCost(game,inputTokensPerPlayer=100){const requests=Object.keys(game.submissions).length,tokens=requests*inputTokensPerPlayer;return{requests,estimatedInputTokens:tokens,estimatedCostUsd:estimateCostUsd(tokens)}}
